"""Claude Code and OpenClaw parsers and the ingest paths they use."""

import io
import json
import sqlite3
import zipfile
from pathlib import Path

import zstandard

from synthsift.harnesses import sniff_parser
from synthsift.harnesses.claude_code import ClaudeCodeParser
from synthsift.harnesses.openclaw import OpenClawParser
from synthsift.ingest import read_zip

ROOT = Path(__file__).resolve().parents[1]


# ----------------------------------------------------------------- Claude Code
def cc_row(typ, uid, parent=None, **fields):
    return {"parentUuid": parent, "isSidechain": False, "userType": "external", "cwd": "/home/alice/proj",
            "sessionId": "s-1", "version": "2.1.90", "gitBranch": "main", "type": typ, "uuid": uid,
            "timestamp": f"2026-06-01T10:00:{int(uid[1:]):02d}.000Z", **fields}


def cc_jsonl(rows):
    return "".join(json.dumps(r) + "\n" for r in rows).encode()


def assistant(uid, msg_id, block, model="claude-sonnet-5", **extra):
    return cc_row("assistant", uid, message={"id": msg_id, "role": "assistant", "model": model, "content": [block]}, **extra)


def user(uid, content, **extra):
    return cc_row("user", uid, message={"role": "user", "content": content}, **extra)


CC_ROWS = [
    {"type": "ai-title", "aiTitle": "Fix the flaky test", "sessionId": "s-1"},
    user("u01", "The test in tests/test_io.py is flaky, please fix it"),
    assistant("u02", "msg_a", {"type": "thinking", "thinking": "Read the test first."}),
    assistant("u03", "msg_a", {"type": "text", "text": "Reading it."}),
    assistant("u04", "msg_a", {"type": "tool_use", "id": "t1", "name": "Read", "input": {"file_path": "tests/test_io.py"}}),
    user("u05", [{"type": "tool_result", "tool_use_id": "t1",
                  "content": "def test_io(): ...\n<system-reminder>Check for malware.</system-reminder>"}]),
    user("u06", "<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>opus</command-args>"),
    user("u07", "<local-command-stdout>Set model to opus</local-command-stdout>"),
    user("u08", "<bash-input>git status</bash-input>"),
    user("u09", "<bash-stdout>M tests/test_io.py</bash-stdout><bash-stderr></bash-stderr>"),
    user("u10", "<local-command-caveat>Caveat: generated by local commands</local-command-caveat>", isMeta=True),
    cc_row("attachment", "u11", attachment={"type": "queued_command", "prompt": "also run the linter"}),
    cc_row("attachment", "u12", attachment={"type": "deferred_tools_record", "entries": []}),
    {"type": "last-prompt", "lastPrompt": "x", "sessionId": "s-1"},
    cc_row("system", "u13", subtype="compact_boundary", content="Conversation compacted",
           compactMetadata={"trigger": "auto", "preTokens": 150000}),
    user("u14", "This session is being continued from a previous conversation…", isCompactSummary=True),
    assistant("u15", "msg_b", {"type": "text", "text": "API Error: overloaded"}, model="<synthetic>", isApiErrorMessage=True),
    # a sub-agent interleaved in the same file (older layout)
    {**user("u16", "Search the repo for sleep() calls"), "isSidechain": True, "agentId": "ag1"},
    {**assistant("u17", "msg_c", {"type": "tool_use", "id": "t2", "name": "Grep", "input": {"pattern": "sleep\\("}},
                 model="claude-haiku-4-5"), "isSidechain": True, "agentId": "ag1"},
    {**user("u18", [{"type": "tool_result", "tool_use_id": "t2", "content": [{"type": "text", "text": "tests/test_io.py:3"}]}]),
     "isSidechain": True, "agentId": "ag1"},
    user("u05", [{"type": "tool_result", "tool_use_id": "t1", "content": "duplicate row"}]),  # repeated uuid
]


def test_claude_code_session_structure():
    raw = cc_jsonl(CC_ROWS) + b'{"type": "user", "trunc'  # a live file copied mid-write
    parser = ClaudeCodeParser()
    main, sub = parser.parse(raw, "s-1.jsonl")
    assert parser.warnings == ["skipped 1 unreadable line(s)"]
    assert main.title == "Fix the flaky test" and main.model == "claude-sonnet-5"
    assert main.meta["cwd"] == "/home/alice/proj" and main.meta["project"] == "proj" and main.meta["git_branch"] == "main"

    # streamed rows of one API message become one message
    a = main.messages[1]
    assert a.role == "assistant" and [b.kind for b in a.blocks] == ["thinking", "text", "tool_call"]
    assert a.blocks[2].tool_name == "Read" and a.blocks[2].arguments == {"file_path": "tests/test_io.py"}

    # tool result linked to its call; the harness reminder is split out
    res = main.messages[2]
    assert res.role == "tool" and res.blocks[0].tool_name == "Read" and "system-reminder" not in res.blocks[0].text
    assert main.messages[3].role == "system" and main.messages[3].meta["kind"] == "system_reminder"

    kinds = [(m.role, m.meta.get("kind")) for m in main.messages]
    assert ("user", "command") in kinds and ("system", "command_output") in kinds
    assert ("system", "meta") in kinds and ("user", "queued_prompt") in kinds
    assert ("system", "compact_boundary") in kinds and ("system", "compact_summary") in kinds
    assert ("system", "api_error") in kinds
    cmd = next(m for m in main.messages if m.meta.get("kind") == "command")
    assert cmd.blocks[0].text == "/model opus"

    # "!" bash mode: a shell command the user ran, with its output
    shell = next(m for m in main.messages if m.meta.get("kind") == "user_shell")
    call = shell.blocks[0]
    assert call.kind == "tool_call" and call.tool_name == "user_shell" and call.arguments == {"command": "git status"}
    out = main.messages[main.messages.index(shell) + 1].blocks[0]
    assert out.kind == "tool_result" and out.tool_call_id == call.tool_call_id and out.text == "M tests/test_io.py"

    # no duplicate from the repeated uuid
    assert sum(1 for m in main.messages for b in m.blocks if b.text == "duplicate row") == 0

    # the sub-agent is its own conversation
    assert sub.meta["subagent"] and sub.meta["agent_id"] == "ag1" and sub.meta["parent_session_id"] == "s-1"
    assert sub.title.startswith("Sub-agent: Search the repo") and sub.model == "claude-haiku-4-5"
    assert [m.role for m in sub.messages] == ["user", "assistant", "tool"]


def test_claude_code_subagent_file_and_non_transcripts():
    rows = [{**user("u01", "Look up the docs"), "isSidechain": True, "agentId": "a7"},
            {**assistant("u02", "m1", {"type": "text", "text": "Done."}), "isSidechain": True, "agentId": "a7"}]
    [conv] = ClaudeCodeParser().parse(cc_jsonl(rows), "agent-a7.jsonl")
    assert conv.meta["subagent"] and conv.meta["agent_id"] == "a7" and conv.title == "Sub-agent: Look up the docs"
    # files that live next to transcripts but are not transcripts
    assert ClaudeCodeParser().parse(b'{\n  "permissions": {"allow": []}\n}\n', "settings.json") == []
    assert ClaudeCodeParser().parse(b'[{"content": "todo", "status": "pending"}]', "todos.json") == []
    assert ClaudeCodeParser().parse(b'{"display": "hi", "timestamp": 1}\n', "history.jsonl") == []


def test_claude_code_sniffing():
    assert sniff_parser(cc_jsonl(CC_ROWS), "x.jsonl").name == "claude_code"


# --------------------------------------------------------------------- OpenClaw
def oc_events():
    t = "2026-06-24T07:31:0{}.000Z"
    return [
        {"type": "session", "version": 3, "id": "oc-1", "timestamp": t.format(0), "cwd": "/home/max/.openclaw/workspace"},
        {"type": "model_change", "id": "e1", "parentId": None, "timestamp": t.format(1), "provider": "anthropic",
         "modelId": "claude-sonnet-5"},
        {"type": "message", "id": "e2", "parentId": "e1", "timestamp": t.format(2),
         "message": {"role": "user", "content": [{"type": "text", "text": "[Telegram Max id:1] list my files"}],
                     "timestamp": 1782286262000}},
        {"type": "message", "id": "e3", "parentId": "e2", "timestamp": t.format(3), "message": {
            "role": "assistant", "provider": "anthropic", "model": "claude-sonnet-5", "stopReason": "toolUse",
            "content": [{"type": "thinking", "thinking": "Use exec."},
                        {"type": "thinking", "thinking": "opaque", "redacted": True},
                        {"type": "toolCall", "id": "c1", "name": "exec", "arguments": {"command": "ls ~/docs"}}]}},
        {"type": "message", "id": "e4", "parentId": "e3", "timestamp": t.format(4), "message": {
            "role": "toolResult", "toolCallId": "c1", "toolName": "exec", "isError": False,
            "content": [{"type": "text", "text": "cv.pdf\ntaxes-2025.xlsx"}]}},
        {"type": "message", "id": "e5", "parentId": "e4", "timestamp": t.format(5), "message": {
            "role": "user", "content": "[Inter-session message] isUser=false\nstop", "provenance": {"kind": "inter_session"}}},
        {"type": "message", "id": "e6", "parentId": "e5", "timestamp": t.format(6), "message": {
            "role": "user", "content": "runtime context", "runtimeContextCarrier": True}},
        {"type": "message", "id": "e7", "parentId": "e6", "timestamp": t.format(7), "message": {
            "role": "bashExecution", "command": "uptime", "output": "up 3 days", "exitCode": 0}},
        {"type": "message", "id": "e8", "parentId": "e7", "timestamp": t.format(8), "message": {
            "role": "assistant", "provider": "openai", "model": "gpt-5-mini", "stopReason": "error",
            "errorMessage": "rate limited", "content": []}},
        {"type": "compaction", "id": "e9", "parentId": "e8", "timestamp": t.format(9), "summary": "Listed files.",
         "firstKeptEntryId": "e8", "tokensBefore": 1000},
        {"type": "custom", "id": "e10", "parentId": "e9", "customType": "ext-state", "data": {}},
    ]


def jsonl(rows):
    return "".join(json.dumps(r) + "\n" for r in rows).encode()


def test_openclaw_event_stream():
    [conv] = OpenClawParser().parse(jsonl(oc_events()), "oc-1.jsonl")
    assert conv.meta["session_id"] == "oc-1" and conv.meta["cwd"] == "/home/max/.openclaw/workspace"
    assert conv.model == "anthropic/claude-sonnet-5" and conv.started_at == "2026-06-24T07:31:00.000Z"
    roles = [(m.role, m.meta.get("kind") or ("inter_session" if m.meta.get("inter_session") else None)) for m in conv.messages]
    assert roles == [("user", None), ("assistant", None), ("tool", None), ("user", "inter_session"),
                     ("system", "runtime_context"), ("user", "user_shell"), ("tool", None),
                     ("system", "model_error"), ("system", "compaction")]
    a = conv.messages[1]
    assert [b.kind for b in a.blocks] == ["thinking", "tool_call"]  # redacted thinking dropped
    assert a.blocks[1].tool_name == "exec" and a.blocks[1].arguments == {"command": "ls ~/docs"}
    assert conv.messages[2].blocks[0].tool_name == "exec" and conv.messages[2].blocks[0].tool_call_id == "c1"
    assert conv.messages[5].blocks[0].arguments == {"command": "uptime"}


def test_openclaw_archives_and_index_files():
    blob = zstandard.ZstdCompressor().compress(jsonl(oc_events()))
    [conv] = OpenClawParser().parse(blob, "oc-1.jsonl.deleted.2026-06-25T08-00-00Z.zst")
    assert conv.meta["archive"] == "deleted"
    # the legacy sessions.json index is not a transcript
    assert OpenClawParser().parse(b'{\n  "agent:main:main": {"sessionId": "oc-1"}\n}\n', "sessions.json") == []
    assert sniff_parser(jsonl(oc_events()), "x.jsonl").name == "openclaw"


def make_db(path: Path, wal: bool = False) -> sqlite3.Connection:
    con = sqlite3.connect(path)
    if wal:
        con.execute("PRAGMA journal_mode=WAL")
        con.execute("PRAGMA wal_autocheckpoint=0")
    con.executescript("""
        CREATE TABLE transcript_events (session_id TEXT, seq INTEGER, event_json TEXT, event_zstd BLOB, created_at INTEGER);
        CREATE TABLE session_windows (session_id TEXT, session_key TEXT, channel TEXT, chat_type TEXT, display_name TEXT,
                                      model TEXT, model_provider TEXT, started_at INTEGER);
        CREATE TABLE session_nodes (session_key TEXT, current_session_id TEXT, label TEXT, display_name TEXT);
        CREATE TABLE session_transcript_archives (session_id TEXT, session_key TEXT, archive_name TEXT, archive_blob BLOB,
                                                  encoding TEXT, reason TEXT, created_at INTEGER);
    """)
    z = zstandard.ZstdCompressor()
    for seq, ev in enumerate(oc_events()):
        text = json.dumps(ev)
        if seq % 2:  # mix plain and compressed rows
            con.execute("INSERT INTO transcript_events VALUES (?,?,?,?,?)", ("oc-1", seq, None, z.compress(text.encode()), seq))
        else:
            con.execute("INSERT INTO transcript_events VALUES (?,?,?,?,?)", ("oc-1", seq, text, None, seq))
    con.execute("INSERT INTO session_windows VALUES ('oc-1', 'agent:work:telegram:direct:1', 'telegram', 'direct', "
                "'Files', 'claude-sonnet-5', 'anthropic', 1782286260000)")
    con.execute("INSERT INTO session_nodes VALUES ('agent:work:telegram:direct:1', 'oc-1', 'My files', NULL)")
    gone = [dict(e, id=e.get("id")) for e in oc_events()[:5]]
    gone[0]["id"] = "oc-2"
    con.execute("INSERT INTO session_transcript_archives VALUES (?,?,?,?,?,?,?)",
                ("oc-2", "agent:work:whatsapp:direct:2", "oc-2.jsonl.deleted.2026-06-25T08-00-00Z.zst",
                 z.compress(jsonl(gone)), "zstd", "manual", 1782374400000))
    con.commit()
    return con


def test_openclaw_sqlite(tmp_path):
    make_db(tmp_path / "a.sqlite").close()
    parser = OpenClawParser()
    convs = parser.parse((tmp_path / "a.sqlite").read_bytes(), "openclaw-agent.sqlite")
    assert not parser.warnings
    live, deleted = sorted(convs, key=lambda c: c.meta.get("archive", ""))
    assert live.title == "My files" and live.meta["channel"] == "telegram" and live.meta["agent"] == "work"
    assert live.meta["session_key"] == "agent:work:telegram:direct:1"
    assert sum(len(m.blocks) for m in live.messages) >= 9  # compressed rows were decoded
    assert deleted.meta["archive"] == "deleted" and deleted.meta["archive_reason"] == "manual"
    assert deleted.meta["session_id"] == "oc-2"
    assert sniff_parser((tmp_path / "a.sqlite").read_bytes(), "x.sqlite").name == "openclaw"
    # an unrelated SQLite file
    other = tmp_path / "b.sqlite"
    sqlite3.connect(other).execute("CREATE TABLE t (x)").connection.close()
    p = OpenClawParser()
    assert p.parse(other.read_bytes(), "b.sqlite") == [] and "no transcript_events" in p.warnings[0]


def test_openclaw_sqlite_reads_the_write_ahead_log(tmp_path):
    db = tmp_path / "live.sqlite"
    con = make_db(db, wal=True)  # still open: the rows only exist in live.sqlite-wal
    try:
        main_only = OpenClawParser().parse(db.read_bytes(), "live.sqlite")
        parser = OpenClawParser()
        parser.companions = {"-wal": Path(f"{db}-wal").read_bytes()}
        with_wal = parser.parse(db.read_bytes(), "live.sqlite")
    finally:
        con.close()
    assert main_only == [] and len(with_wal) == 2


# ----------------------------------------------------------------------- ingest
def test_ingest_agent_state_folders_and_archives(tmp_path):
    make_db(tmp_path / "db.sqlite").close()
    blob = zstandard.ZstdCompressor().compress(jsonl(oc_events()))
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        # a zip of the raw hidden folders: user comes from the Claude Code project path
        zf.writestr(".claude/projects/-home-alice-proj/s-1.jsonl", cc_jsonl(CC_ROWS))
        zf.writestr(".claude/settings.json", '{\n  "model": "opus"\n}\n')
        zf.writestr("srv/max/openclaw/agents/work/agent/openclaw-agent.sqlite", (tmp_path / "db.sqlite").read_bytes())
        zf.writestr("srv/max/openclaw/agents/work/sessions/oc-9.jsonl.deleted.2026-06-25T08-00-00Z.zst", blob)
        zf.writestr("srv/max/openclaw/agents/work/sessions/sessions.json", '{\n  "a": {}\n}\n')
        zf.writestr("srv/max/openclaw/agents/work/sessions/oc-9.jsonl.lock", '{"pid": 1}')
    rep = read_zip(buf.getvalue(), "ds")
    assert not rep.warnings
    got = sorted((c.host, c.user, c.harness, c.meta.get("archive", "")) for c in rep.conversations)
    assert got == [("srv", "max", "openclaw", ""), ("srv", "max", "openclaw", "deleted"), ("srv", "max", "openclaw", "deleted"),
                   ("unknown-host", "alice", "claude_code", ""), ("unknown-host", "alice", "claude_code", "")]


def test_samples_include_every_agent():
    rep = read_zip((ROOT / "samples" / "synthsift-samples.zip").read_bytes(), "s")
    assert not rep.warnings
    by_harness = {}
    for c in rep.conversations:
        by_harness.setdefault(c.harness, []).append(c)
    assert len(by_harness["claude_code"]) == 4 and len(by_harness["openclaw"]) == 4
    assert len(by_harness["gemini"]) == 4 and len(by_harness["antigravity"]) == 3
    assert {c.meta.get("app") for c in by_harness["antigravity"]} == {"Antigravity CLI", "Antigravity IDE", None}
    titles = {c.display_title for c in by_harness["openclaw"]}
    assert {"Groceries & dentist", "#homelab"} <= titles


def test_security_findings_on_agent_samples(sample_workspace):
    ws = sample_workspace
    harness = {c.id: c.harness for c in ws.conversations}
    got = {(harness[f.conv], f.rule) for f in ws.findings if harness[f.conv] != "example"}
    assert {("claude_code", "sensitive_path"), ("claude_code", "exfiltration"), ("openclaw", "exfiltration")} <= got
